package community.xueshi.model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.ID
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.TITLE
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.DESCRIPTION
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.GMTCREATOR
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    private Long gmtcreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.GMTMODIFIED
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    private Long gmtmodified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.CREATOR
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.COMMENTCOUNT
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    private Integer commentcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.VIEWCOUNT
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    private Integer viewcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.LIKECOUNT
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    private Integer likecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.TAG
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.ID
     *
     * @return the value of QUESTION.ID
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.ID
     *
     * @param id the value for QUESTION.ID
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.TITLE
     *
     * @return the value of QUESTION.TITLE
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.TITLE
     *
     * @param title the value for QUESTION.TITLE
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.DESCRIPTION
     *
     * @return the value of QUESTION.DESCRIPTION
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.DESCRIPTION
     *
     * @param description the value for QUESTION.DESCRIPTION
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.GMTCREATOR
     *
     * @return the value of QUESTION.GMTCREATOR
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public Long getGmtcreator() {
        return gmtcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.GMTCREATOR
     *
     * @param gmtcreator the value for QUESTION.GMTCREATOR
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public void setGmtcreator(Long gmtcreator) {
        this.gmtcreator = gmtcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.GMTMODIFIED
     *
     * @return the value of QUESTION.GMTMODIFIED
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public Long getGmtmodified() {
        return gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.GMTMODIFIED
     *
     * @param gmtmodified the value for QUESTION.GMTMODIFIED
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public void setGmtmodified(Long gmtmodified) {
        this.gmtmodified = gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.CREATOR
     *
     * @return the value of QUESTION.CREATOR
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.CREATOR
     *
     * @param creator the value for QUESTION.CREATOR
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.COMMENTCOUNT
     *
     * @return the value of QUESTION.COMMENTCOUNT
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public Integer getCommentcount() {
        return commentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.COMMENTCOUNT
     *
     * @param commentcount the value for QUESTION.COMMENTCOUNT
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public void setCommentcount(Integer commentcount) {
        this.commentcount = commentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.VIEWCOUNT
     *
     * @return the value of QUESTION.VIEWCOUNT
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public Integer getViewcount() {
        return viewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.VIEWCOUNT
     *
     * @param viewcount the value for QUESTION.VIEWCOUNT
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public void setViewcount(Integer viewcount) {
        this.viewcount = viewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.LIKECOUNT
     *
     * @return the value of QUESTION.LIKECOUNT
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public Integer getLikecount() {
        return likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.LIKECOUNT
     *
     * @param likecount the value for QUESTION.LIKECOUNT
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public void setLikecount(Integer likecount) {
        this.likecount = likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.TAG
     *
     * @return the value of QUESTION.TAG
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.TAG
     *
     * @param tag the value for QUESTION.TAG
     *
     * @mbg.generated Thu Jul 21 15:08:52 BST 2022
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }
}