package community.xueshi.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR.ID
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR.ACCOUNT_ID
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR.NAME
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR.TOKEN
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR.GMT_CREATE
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR.GMT_MODIFIED
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR.BIO
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USR.AVATAR_URL
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR.ID
     *
     * @return the value of USR.ID
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR.ID
     *
     * @param id the value for USR.ID
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR.ACCOUNT_ID
     *
     * @return the value of USR.ACCOUNT_ID
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR.ACCOUNT_ID
     *
     * @param accountId the value for USR.ACCOUNT_ID
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR.NAME
     *
     * @return the value of USR.NAME
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR.NAME
     *
     * @param name the value for USR.NAME
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR.TOKEN
     *
     * @return the value of USR.TOKEN
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR.TOKEN
     *
     * @param token the value for USR.TOKEN
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR.GMT_CREATE
     *
     * @return the value of USR.GMT_CREATE
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR.GMT_CREATE
     *
     * @param gmtCreate the value for USR.GMT_CREATE
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR.GMT_MODIFIED
     *
     * @return the value of USR.GMT_MODIFIED
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR.GMT_MODIFIED
     *
     * @param gmtModified the value for USR.GMT_MODIFIED
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR.BIO
     *
     * @return the value of USR.BIO
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR.BIO
     *
     * @param bio the value for USR.BIO
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USR.AVATAR_URL
     *
     * @return the value of USR.AVATAR_URL
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USR.AVATAR_URL
     *
     * @param avatarUrl the value for USR.AVATAR_URL
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }
}