package community.xueshi.mapper;

import community.xueshi.model.User;
import community.xueshi.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    int updateByExample(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USR
     *
     * @mbg.generated Tue Jul 19 22:28:27 BST 2022
     */
    int updateByPrimaryKey(User row);
}